color0 #15121a
color1 #ffb4ab
color2 #d2bbff
color3 #d1bef5
color4 #ffaedc
color5 #d2bbff
color6 #d1bef5
color7 #e7e0eb
color8 #958e9e
color9 #ffb4ab
color10 #d2bbff
color11 #d1bef5
color12 #ffaedc
color13 #d2bbff
color14 #d1bef5
color15 #e7e0eb

cursor                #e7e0eb
cursor_text_color     #15121a
background            #15121a
foreground            #e7e0eb
selection_foreground  #ccc3d5
selection_background  #4a4453
active_border_color   #d2bbff
inactive_border_color #4a4453
url_color             #d2bbff
